### ISSUE TITLE
Realm Recyclerview not working with Realm 3.5.0

### ISSUE THREAD

**Issue by trixzter** [thorbenprimke/realm-recyclerview#117]
I have implemented the RealmRecyclerView in my app. In this site https://academy.realm.io/posts/android-realm-listview/ they said that the version of realm recyclerview is 0.9.5. But together with the 3.5.0 version of realm, some methods of realm are lost, like init, deleteAllFromRealm. Then I changed the version of realm recyclerview to 0.9.25. The methods of realm are present again but then I get this error when running my program:

java.lang.NoSuchMethodError: No virtual method getTableOrView()Lio/realm/internal/TableOrView; in class Lio/realm/RealmResults; or its super classes (declaration of 'io.realm.RealmResults' appears in /data/app/com.tasks.bryanvillanueva.retrofitpractice-1/split_lib_dependencies_apk.apk:classes7.dex)
                                                     at io.realm.RealmBasedRecyclerViewAdapter.<init>(RealmBasedRecyclerViewAdapter.java:167)
                                                     at io.realm.RealmBasedRecyclerViewAdapter.<init>(RealmBasedRecyclerViewAdapter.java:133)
                                                     at io.realm.RealmBasedRecyclerViewAdapter.<init>(RealmBasedRecyclerViewAdapter.java:123)

When I changed the version of realm to 2.2.1 everything is fine. I just wanted to know what causes the error when using 3.5.0? Is it not supported yet?

**Comment by Zhuinden** [comment]
The error is caused by that Realm has completed its object store results integration in Realm 3.0, which also had the internal api `getTableOrView()` removed.

But generally you should want to give the official https://github.com/realm/realm-android-adapters a try.
